[config]
reload_apps = false
set_wallpaper = false

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf"
output_path = "~/.config/kitty/colors.conf"
post_hook = "pkill -USR1 kitty"

[templates.waybar]
input_path = "~/.config/matugen/templates/matugen-waybar.css"
output_path = "~/.config/waybar/colors.css"
post_hook = "pkill -SIGUSR2 waybar"

[templates.rofi]
input_path = '~/.config/matugen/templates/matugen-rofi.rasi'
output_path = '~/.config/rofi/matugen/matugen-rofi.rasi'

[templates.hyprland]
input_path = '~/.config/matugen/templates/matugen-hyprland.conf'
output_path = '~/.config/hypr/matugen/matugen-hyprland.conf'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/matugen-hyprlock.conf'
output_path = '~/.config/hypr/hyprlock/matugen/matugen-hyprlock.conf'

[templates.gtk3]
input_path = '~/.config/matugen/templates/matugen-gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/matugen-gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'
