-- Generated by matugen from /home/xera/.dotfiles/wallpapers/Pictures/Wallpapers/R34 New.png — do not edit by hand.
return {

    background = "111418",

    error = "ffb4ab",

    error_container = "93000a",

    inverse_on_surface = "2e3135",

    inverse_primary = "38608f",

    inverse_surface = "e1e2e8",

    on_background = "e1e2e8",

    on_error = "690005",

    on_error_container = "ffdad6",

    on_primary = "00325a",

    on_primary_container = "d2e4ff",

    on_primary_fixed = "001c37",

    on_primary_fixed_variant = "1c4975",

    on_secondary = "253141",

    on_secondary_container = "d7e3f8",

    on_secondary_fixed = "101c2b",

    on_secondary_fixed_variant = "3c4858",

    on_surface = "e1e2e8",

    on_surface_variant = "c3c6cf",

    on_tertiary = "3c2947",

    on_tertiary_container = "f4daff",

    on_tertiary_fixed = "261431",

    on_tertiary_fixed_variant = "533f5f",

    outline = "8d9199",

    outline_variant = "43474e",

    primary = "a2c9fd",

    primary_container = "1c4975",

    primary_fixed = "d2e4ff",

    primary_fixed_dim = "a2c9fd",

    scrim = "000000",

    secondary = "bbc7db",

    secondary_container = "3c4858",

    secondary_fixed = "d7e3f8",

    secondary_fixed_dim = "bbc7db",

    shadow = "000000",

    source_color = "116db8",

    surface = "111418",

    surface_bright = "37393e",

    surface_container = "1d2024",

    surface_container_high = "272a2f",

    surface_container_highest = "32353a",

    surface_container_low = "191c20",

    surface_container_lowest = "0b0e13",

    surface_dim = "111418",

    surface_tint = "a2c9fd",

    surface_variant = "43474e",

    tertiary = "d8bde4",

    tertiary_container = "533f5f",

    tertiary_fixed = "f4daff",

    tertiary_fixed_dim = "d8bde4",

}
