font_size 13.0
window_padding_width 8
font_family      JetBrainsMono Nerd Font
italic_font      auto
# bold_font        auto
bold_italic_font auto
include theme.conf
#background_opacity 0.60
#hide_window_decorations yes
#confirm_os_window_close 0
#

# Split keybinds
map ctrl+shift+d launch --location=vsplit --cwd=current
map ctrl+shift+s launch --location=hsplit --cwd=current
map ctrl+shift+w close_window

# Panel arası geçiş
map ctrl+shift+left neighboring_window left
map ctrl+shift+right neighboring_window right
map ctrl+shift+up neighboring_window up
map ctrl+shift+down neighboring_window down

enabled_layouts splits
