# Configuration
font_family                  JetBrainsMono Nerd Font
font_size                    13.0
bold_font                    auto
italic_font                  auto
bold_italic_font             auto

remember_window_size         no
initial_window_width         950
initial_window_height        500

cursor_blink_interval        0.5
cursor_stop_blinking_after   1
cursor_trail                 1
cursor_trail_decay           0.1 0.4
cursor_trail_start_threshold 6

scrollback_lines             2000
wheel_scroll_min_lines       1
enable_audio_bell            no

window_padding_width         10
hide_window_decorations      yes
background_opacity           1.0
dynamic_background_opacity   yes
confirm_os_window_close      0

linux_display_server         wayland
shell                        zsh


# Keybinds
kitty_mod ctrl+shift

# Opacity
map kitty_mod+p set_background_opacity -0.1
map kitty_mod+o set_background_opacity +0.1
map kitty_mod+shift+o set_background_opacity default

# Font size
map kitty_mod+shift+page_up change_font_size all +2.0
map kitty_mod+shift+page_down change_font_size all -2.0
map kitty_mod+shift+backspace change_font_size all 0

# Scroll
map page_up scroll_page_up
map page_down scroll_page_down

# Reload config
map kitty_mod+r load_config_file

# Splits
map ctrl+shift+d launch --location=vsplit --cwd=current
map ctrl+shift+s launch --location=hsplit --cwd=current
map ctrl+shift+w close_window

# Panel navigation
map ctrl+shift+left  neighboring_window left
map ctrl+shift+right neighboring_window right
map ctrl+shift+up    neighboring_window up
map ctrl+shift+down  neighboring_window down

enabled_layouts splits


# Colors
include theme.conf
include colors.conf
